name: Update latest

on:
  schedule:
   - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-latest:
    name: Update latest
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add and update test environments
        run: python .github/workflows/latest.py

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.KITTENOAK_PAT }}
          push-to-fork: kittenoak/anki-delay-siblings
          title: ${{ env.PR_TITLE }}
          commit-message: ${{ env.COMMIT_MESSAGE }}